import colors
from colors import bcolors
print("MESSAGE COLORS")
# print(bcolors.HEADER + "probando HEADER"+bcolors.ENDC)
# print("wiiiiiiiiiiiiiiiiiiiiiiii")
# print(bcolors.OKBLUE + "Que tal este azul para los mensajes?"+bcolors.ENDC) # posible letras
# print(bcolors.OKGREEN + "probando OKGREEN"+bcolors.ENDC)
# print(bcolors.WARNING + "probando WARNING"+bcolors.ENDC)
print(bcolors.BOLD+bcolors.FAIL + "probando FAIL"+bcolors.ENDC)
# print(bcolors.ENDC + "probando ENDC"+bcolors.ENDC)
# print(bcolors.BOLD + "probando BOLD"+bcolors.ENDC)
# print(bcolors.UNDERLINE + "probando UNDERLINE"+bcolors.ENDC)
# print("FOREGROUND COLORS"+bcolors.ENDC)
# print(bcolors.black + "probando black"+bcolors.ENDC)
# print(bcolors.red + "probando red"+bcolors.ENDC)
# print(bcolors.green + "probando green"+bcolors.ENDC)
# print(bcolors.orange + "probando orange"+bcolors.ENDC)
# print(bcolors.blue + "probando blue"+bcolors.ENDC)
# print(bcolors.purple + "probando purple"+bcolors.ENDC)
# print(bcolors.cyan + "probando cyan"+bcolors.ENDC)
# print(bcolors.lightgrey + "probando lightgrey"+bcolors.ENDC)
# print(bcolors.darkgrey + "probando darkgrey"+bcolors.ENDC)
# print(bcolors.lightred + "probando lightred"+bcolors.ENDC)
# print(bcolors.lightgreen + "probando lightgreen"+bcolors.ENDC)
# print(bcolors.yellow + "probando yellow"+bcolors.ENDC)
# print(bcolors.lightblue + "probando lightblue"+bcolors.ENDC)
# print(bcolors.pink + "probando pink"+bcolors.ENDC)
# print(bcolors.lightcyan + "probando lightcyan"+bcolors.ENDC)
# print("BACKGROUND COLORS"+bcolors.ENDC)
# print(bcolors.bblack + "probando black"+bcolors.ENDC)
# print(bcolors.bred + "probando red"+bcolors.ENDC)
# print(bcolors.bgreen + "probando green"+bcolors.ENDC)
# print(bcolors.borange + "probando orange"+bcolors.ENDC)
# print(bcolors.bblue + "probando blue"+bcolors.ENDC)
# print(bcolors.bpurple + "probando purple"+bcolors.ENDC)
# print(bcolors.bcyan + "probando cyan"+bcolors.ENDC)
# print(bcolors.blightgrey + "probando lightgrey'"+bcolors.ENDC)